LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := events.c resources.c chinese.c
ifneq ($(BOARD_CUSTOM_GRAPHICS),)
  LOCAL_SRC_FILES += $(BOARD_CUSTOM_GRAPHICS)
else
  LOCAL_SRC_FILES += graphics.c
endif

LOCAL_C_INCLUDES +=\
    external/libpng\
    external/zlib

LOCAL_MODULE := libminui

ifeq ($(TARGET_RECOVERY_PIXEL_FORMAT),"RGBX_8888")
  LOCAL_CFLAGS += -DRECOVERY_RGBX
endif
ifeq ($(TARGET_RECOVERY_PIXEL_FORMAT),"BGRA_8888")
  LOCAL_CFLAGS += -DRECOVERY_BGRA
endif

ifneq ($(BOARD_USE_CUSTOM_RECOVERY_FONT),)
  LOCAL_CFLAGS += -DBOARD_USE_CUSTOM_RECOVERY_FONT=\"$(BOARD_USE_CUSTOM_RECOVERY_FONT)\"
endif

ifneq ($(TARGET_USES_CUSTOM_VIBRATOR_PATH),)
  LOCAL_CFLAGS += -DTARGET_USES_CUSTOM_VIBRATOR_PATH=\"$(TARGET_USES_CUSTOM_VIBRATOR_PATH)\"
endif

ifneq ($(DEBUG_TOUCHSCREEN),)
LOCAL_CFLAGS += -DDEBUG_TOUCHSCREEN=$(DEBUG_TOUCHSCREEN)
endif

ifneq ($(MAX_TOUCH_X),)
  LOCAL_CFLAGS += -DMAX_TOUCH_X=$(MAX_TOUCH_X)
endif

ifneq ($(MAX_TOUCH_Y),)
  LOCAL_CFLAGS += -DMAX_TOUCH_Y=$(MAX_TOUCH_Y)
endif

ifneq ($(MIN_TOUCH_X),)
  LOCAL_CFLAGS += -DMIN_TOUCH_X=$(MIN_TOUCH_X)
endif

ifneq ($(MIN_TOUCH_Y),)
  LOCAL_CFLAGS += -DMIN_TOUCH_Y=$(MIN_TOUCH_Y)
endif

include $(BUILD_STATIC_LIBRARY)
